### PR TITLE
fix bg bleed in git diff for whitespace errors

### PR DESCRIPTION
**Pull request by rkitover**
Alter the end pattern for the Bg syn regions in AnsiEsc to also match
the pattern git uses to reset ANSI colors, namely \e[m .

There is still an issue with vim's conceal regions screwing up how many
spaces vim thinks is a tab, not sure how to fix this in AnsiEsc, we make
vimpager use a crude hack to work around this: force a :retab.

### CODE REVIEW

**Comment by zeekay** [comment]
@rkitover Just out of curiosity, if you are using AnsiEsc, how do configure vimpager to interact with it? I've been using both vimpager and AnsiEsc for a couple years and I manually remove the `sed` lines that strip ANSI colors from vimpager.

**Comment by rkitover** [comment]
This is new stuff in my master for vimpager, I made a bundling mechanism and I bundle this version (with this patch) of AnsiEsc which is expanded at runtime with uudecode and tar.

I still have issues with making spacing correct in git diffs, once I fix that I will do a release.

**Comment by rkitover** [comment]
@zeekay Hi, are you going to merge this? Or is my PR hillariously wrong in some way, in which case I'll be happy to redo it. I'm not an expert on ANSI escape codes or anything.

**Comment by powerman** [comment]
Sorry for "delayed" response. Looks like I've decided to research what you're trying to fix and what is right way to do this and then was distracted by other tasks. I have nothing against merging your PR as soon as I'll understand what exactly you're trying to fix and will be able to test this myself. Can you please provide example file (or, better, any standard command which produce such output) to demonstrate issue you're trying to fix?

**Comment by rkitover** [comment]
I rebased and added a couple of other commits. One is from a contributor to vimpager, the other is another fix I just did.

As for the bg bleed issue, here is how you can easily reproduce this:
- in some git project, add a line with a few leading spaces and nothing else
- git diff HEAD > foo
- vim foo
- :AnsiEsc

**Comment by rkitover** [comment]
@powerman Hi, I have rewritten the three commits according to your directions, can you please check if everything is correct? Especially the code 49 stuff.

Please don't merge yet, I added the file try.ansi submitted in an issue for vimpager, I didn't notice that it doesn't work fully yet, I want to fix all the remaining issues before this is closed.

Or if you want to merge, I will send a separate PR for fixing this file.

Thank you!

**Comment by powerman** [comment]
@rkitover At a glance everything looks good! Let me know when it'll be ready for merge.

**Comment by rkitover** [comment]
I found an issue with the syn clusters, try this pattern out:
\e[47m\e[30mFOO\e[0m
this should match ansiFgBlackWhite but it only matches ansiWhiteBg.

My vim is from homebrew: 7.4 patches 1-712

Also I was thinking it would be good to write a test suite for this project, what is your preferred testing framework? I was just going to use PyUnit or some such.

**Comment by powerman** [comment]
I suppose this happens because of typos - cluster names begins with upper case `syn cluster AnsiWhiteBgGroup` but then they included with lower case `contains=ansiConceal,@ansiWhiteBgGroup`.

As for testing framework I prefer using TAP-compatible tests (Test Anything Protocol), usually written in Perl but they can be in any language. But I'm not sure how to implement usual unit tests for this vim plugin.

**Comment by rkitover** [comment]
Unfortunately that is not the issue, I tried capitalizing the group link but it did not help. I will do some research on this and try to fix them. I noticed this when I was adding a new syn cluster and testing it.

Here is a mapping I made for debugging syntaxes that you may find useful:

``` vim
" echo syntax item under cursor
nmap <F5> :echo synIDattr(synID(line("."), col("."), 1), "name")<CR>
```

this lets you move the cursor to a highlighted area and press F5 to see what the syntax group that matches that area is.

As for testing, I am a CPAN author so I can definitely do perl. I just prefer to start new work in Python or Scala these days, but I am happing to do the test suite beginnings in perl.

As for how to test, it's pretty simple, we can compare ansi snippets to a run of them through vimcat with AnsiEsc enabled, if they are identical the test passes.

**Comment by powerman** [comment]
I use these mappings. Last two works permanently as cursor moves. The downside you can't switch them off. :)

``` vim
nmap <silent> <Leader>hi    :echo
    \     "hi<" . synIDattr(           synID(line("."),col("."),1) ,"name") . ">" .
    \ " trans<" . synIDattr(           synID(line("."),col("."),0) ,"name") . ">" .
    \    " lo<" . synIDattr(synIDtrans(synID(line("."),col("."),1)),"name") . ">"<CR>
nmap <silent> <Leader>HI    :autocmd CursorMoved <buffer> normal \hi<CR>
nmap <silent> <Leader>SS    :autocmd CursorMoved <buffer> :call <SID>SynStack()<CR>
function! s:SynStack()
  echo join(map(synstack(line('.'), col('.')), 'synIDattr(v:val, "name")'), " > ")
endfunc
```

> so I can definitely do perl

Cool. Then please try to implement them in usual way (t/*.t files), so tests can be run using `prove -r`.

**Comment by rkitover** [comment]
Hey @powerman,

I just merged all of my stuff with the updates from the author you made etc.. It was a lot of work.

I added a simple file based test as promised, it's described in detail in the commit message.

I did not reach my goal of making the paws.js file work, the syn clusters are insufficient for this, even with all the ones I added.

At some point in the future I'll rewrite the syn cluster stuff to be dynamic and file based, because there are just too many combinations for this to be static.

If/when I get this stuff merged, the next thing I was planning to do was write a cross-reference test to check all the syn region/match references and their corresponding highlights and make sure all colors exist.

**Comment by powerman** [comment]
Wow, that's a huge work!

I'm sorry, but I'm overloaded with urgent work now, and unlikely will have time to check this in next 5 days. :disappointed: I'll try to keep this on top of my TODO, maybe I'll be able to find a free hour or two in next days and at least start reviewing it.

**Comment by rkitover** [comment]
@powerman 

Hi Alex,

I appreciate the quick response, and none of this is urgent so whenever you have time. I need to switch gears myself and work on some other stuff for a while as well. If I do have any more ideas, I will update this PR.

I would only suggest you make the :%s/none/NONE/g change, because it fixes a serious bug in recent versions of gvim.

**Comment by powerman** [comment]
aee51c2 - Do you think we actually need to support reverse codes? I suppose they're rarely used in real world, and I'm afraid adding so much rules will slowdown Vim. (And paws.js doesn't work correctly anyway (yet).)

0ee13eb - Probably you've missed few places to add "Dark" prefix. E.g. check `t/data/files/bull1_old.ans` - in console left side use dark colors, but in Vim left and right sides use light colors. Looks like related color names are in `fun! s:MultiElementHandler()`.

b079ab1 - Tests won't pass on my system (Failed 7/9 subtests). I'll check it out now. BTW, why you decided to embed dependencies? Not sure about vimcat but colordiff and File::Slurp usually can be installed using package manager/cpanm, and it's enough to check in test they're exists (and have required version, if any).

**Comment by powerman** [comment]
Only passing tests are simple.ansi and vimcat_doc.ansi.

Looks like main issue with other files is vimcat. For example, for file without any Esc-sequences `t/data/files/bull7.ans` command `t/bin/vimcat -o /tmp/vimcat_1 -u NONE -c 'set t_Co=8 | so plugin/cecutil.vim | so autoload/AnsiEsc.vim | call AnsiEsc#AnsiEsc(0)' t/data/files/bull7.ans` produce file with a lot of Esc-sequences in beginning of each line, in Vim it looks this way:

```
^[[22;24;25;27;28;39;49m^[[K^[[22;24;25;27;28;39;49m
^[[22;24;25;27;28;39;49m^[[K^[[22;24;25;27;28;39;49mTHE TOP 10 REASONS ...
^[[22;24;25;27;28;39;49m^[[K^[[22;24;25;27;28;39;49m
^[[22;24;25;27;28;39;49m^[[K^[[22;24;25;27;28;39;49m10. Her commercials ...
...
^[[22;24;25;27;28;39;49m^[[K^[[22;24;25;27;28;39;49m
^[[22;24;25;27;28;39;49m^[[K^[[22;24;25;27;28;39;49m1. The latest Talking ...
^[[22;24;25;27;28;39;49m^[[K^[[22;24;25;27;28;39;49m^[[0m
```

Another (small) issue with this test - it leave a lot of junk files in /tmp, I suppose it's about 3 files per each test, like: /tmp/snsJDwBzOg, /tmp/vimcat__y6fq and /tmp/content_YzRJB.

**Comment by rkitover** [comment]
re reverse clusters: I'm fine with removing the reverse clusters, I'm not particularly attached to them, so I'll do that if you want. I also don't think there should be that many clusters and we really need a dynamic solution of some sort eventually.

re other dark colors: I will check the other colors, good catch there.

re: the tests, yeah only those two pass right now. The others I included just for testing. The codes you see at the beginning of every line from vimcat output are all reset codes that are stripped out. Yes the test is a bit contrived, but that's the best I could do right now and it does seem to work to test basic functionality (like those two files.) You can see in the colordiff output where the codes begin to diverge. The junk files in /tmp are supposed to be removed by File::Temp automatically, at least they are on my system, I will add some code to automatically remove them just in case. I can remove colordiff and File::Slurp if you like, I just put them in because they are small and it saves some effort running the test for someone who knows nothing about perl.

Thanks for taking a look at this stuff.

**Comment by powerman** [comment]
re File::Temp: You probably need to add `UNLINK=>1` to tempfile().

re reverse: We can leave it for now, just to avoid more work for you for removing it, and if no one will complain about slowdown - let it be.

I think it makes sense to merge it at this point, to simplify next development and tracking changes.
When temp files and dark colors will be fixed I'll release new version.

**Comment by rkitover** [comment]
Hi @powerman, it's been a while since we spoke and I have been doing various things and never got around to fixing the outstanding issues here.

I remembered about this because we have a problem with recent versions of gvim and nvim, AnsiEsc does not work in them at all. It loads without errors but there is no highlighting. Terminal vim still works fine.

So I will need to fix this as well as the outstanding issues in this PR.

Also, the whitespace problem is really obnoxious so if I can manage it I'll try to fix this in vim itself. The workaround I made in vimpager only helps so much.

**Comment by powerman** [comment]
Cool. Also you can take a look at #5 - I had plans to implement it myself, but looks like I'll unlikely have enough spare time for this anytime soon. :disappointed:

**Pull request merged**
